# Generated by Django 3.2.15 on 2022-09-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idautor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('ideditora', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('fone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'editora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escreve',
            fields=[
                ('idlivro', models.IntegerField(primary_key=True, serialize=False)),
                ('idautor', models.IntegerField()),
            ],
            options={
                'db_table': 'escreve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensDaVenda',
            fields=[
                ('idvenda', models.IntegerField(primary_key=True, serialize=False)),
                ('idlivro', models.IntegerField()),
                ('qtd', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itens_da_venda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('idlivro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('preco', models.FloatField(blank=True, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('idgenero', models.IntegerField()),
                ('ideditora', models.IntegerField()),
            ],
            options={
                'db_table': 'livro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('idvenda', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('idcliente', models.IntegerField()),
            ],
            options={
                'db_table': 'venda',
                'managed': False,
            },
        ),
    ]
